### ISSUE TITLE
Broken with Latest Karma Version

### ISSUE THREAD

**Issue by DrLongGhost** [markgardner/karma-sets#3]
I tried to get this working and I think I got close...

I needed to change references to browser.launchId in index.js to browser.id. That allowed the tests to kick off but the exit logic seemed broken for me. After running the tests, it would just hang.

**Comment by markgardner** [comment]
I'll take a look. I imagine it will be completely different since I was injecting into karma internals to get it working. Can you create a PR with your work so I could use some of it.

**Comment by DrLongGhost** [comment]
Hi Mark,

I made a PR for the one change. I'm trying to use karma-sets with jasmine and grunt-karma. It seems to get confused about how many tests it should run.

If I have 5 sets, I need to have them listed in both the sets collection AND as attributes of the main karma options object (or the test runner doesn't seem able to find them). But when I put them as attributes, it tries to run the sets and THEN each attribute I also listed.

I've tried hacking around in karma internals to try and get a kludge working, but I'm not making much progress. I really do want to get this "set" functionality available to me so I'm willing to pitch in however I can to help out, but I'm not that familiar with Node or karma internals so I'm only making slow progress.

**Comment by DrLongGhost** [comment]
I made a sample project to show how I am attempting to use karma-sets and the issue I'm running into:  https://github.com/DrLongGhost/grunt-karma-jasmine-sets

Hopefully that will give you an easy test case to find and fix the problem.

Let me know how else I can help.

-Dan

**Comment by markgardner** [comment]
Thanks for the help Dan, I published version 0.1.0 that should fix the issue.

Let me know if it doesn't

**Comment by DrLongGhost** [comment]
Awesome. Thanks for merging that fix.

It looks like I'm getting closer because my project now runs all the tests with the new version from npm without further modifications. However, I am still running into the problem where (I believe) my use of grunt-karma with karma-sets is causing my tests to be run multiple times.

Were you able to grab the test project I mentioned above? You can see the problem in action there. The tests run fine but then it just hangs without exiting. You need to hit control-c multiple times to step through each test run before you can finally get it to exit.

Any idea how I can fix this? For now, I'll be happy with any hack that works. I'd much prefer to stick with grunt-karma but if I ultimately need to move to gulp or even straight karma with just a config file, I guess I can do that if grunt-karma and karma-sets prove too incompatible.
